worker_processes 1;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  log_format main '$remote_addr "$request" $status $body_bytes_sent rt=$request_time urt=$upstream_response_time';
  access_log /var/log/nginx/access.log main;
  resolver 172.28.0.53 valid=10s;
  include /etc/nginx/conf.d/*.conf;
}
